version: '3'

services:
  school_system:
    build: .
    container_name: school_system
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/school_system

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: school_system
      MYSQL_USER: vex
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: